name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify SonarScanner
        shell: cmd
        run: sonar-scanner --version

      - name: Run SonarQube Scan
        shell: cmd
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner -Dsonar.host.url=%SONAR_HOST_URL% -Dsonar.token=%SONAR_TOKEN%
